services:
  - type: web
    name: shenanigans
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_BASE64
        sync: false
